const logos = {
  frontend: [
    {
      id: 1,
      src: "/logo/html-5.png",
      srcDark: "",
      alt: "HTML Logo",
      name: "HTML",
    },
    {
      id: 2,
      src: "/logo/css-3.png",
      srcDark: "",
      alt: "CSS Logo",
      name: "CSS",
    },
    {
      id: 3,
      src: "/logo/bootstrap.png",
      srcDark: "",
      alt: "Bootstrap Logo",
      name: "Bootstrap",
    },
    {
      id: 4,
      src: "/logo/tailwind-css.png",
      srcDark: "",
      alt: "Tailwind CSS",
      name: "Tailwind CSS",
    },
    {
      id: 6,
      src: "/logo/react.png",
      srcDark: "",
      alt: "React JS logo",
      name: "React JS",
    },
    {
      id: 7,
      src: "/logo/nextjs.png",
      srcDark: "/logo/nextjs-dark.png",
      alt: "Next JS logo",
      name: "Next JS",
    },
    {
      id: 8,
      src: "/logo/js.png",
      srcDark: "",
      alt: "JavaScript logo",
      name: "JavaScript",
    },
    {
      id: 9,
      src: "/logo/typescript.png",
      srcDark: "",
      alt: "TypeScript logo",
      name: "TypeScript",
    },
  ],
  backend: [
    {
      id: 10,
      src: "/logo/nodejs.png",
      srcDark: "",
      alt: "Node JS logo",
      name: "Node JS",
    },
    {
      id: 11,
      src: "/logo/mongoose.png",
      srcDark: "",
      alt: "Mongoose logo",
      name: "Mongoose",
    },
    {
      id: 12,
      src: "/logo/express.png",
      srcDark: "/logo/express-dark.png",
      alt: "Express logo",
      name: "Express",
    },
  ],
  database: [
    {
      id: 13,
      src: "/logo/mongodb.png",
      srcDark: "",
      alt: "MongoDB logo",
      name: "MongoDB",
    },
    {
      id: 14,
      src: "/logo/postgresql.png",
      srcDark: "",
      alt: "Postgre logo",
      name: "PostgreSQL",
    },
  ],
  tools: [
    {
      id: 15,
      src: "/logo/render.jpg",
      srcDark: "",
      alt: "Render logo",
      name: "Render",
    },
    {
      id: 16,
      src: "/logo/vercel.png",
      srcDark: "/logo/vercel-dark.png",
      alt: "Vercel logo",
      name: "Vercel",
    },
    { id: 17, src: "/logo/git.png", srcDark: "", alt: "Git logo", name: "Git" },
    {
      id: 18,
      src: "/logo/github.png",
      srcDark: "/logo/github-dark.png",
      alt: "GitHub logo",
      name: "GitHub",
    },
    {
      id: 19,
      src: "/logo/supabase.png",
      srcDark: "",
      alt: "Supabaselogo",
      name: "Supabase",
    },
    {
      id: 20,
      src: "/logo/figma.png",
      srcDark: "",
      alt: "Figma logo",
      name: "Figma",
    },
  ],
  aiIntegrations: [
    {
      id: 21,
      src: "/logo/groq.png",
      srcDark: "/logo/groq-dark.png",
      alt: "Groq logo",
      name: "Groq",
    },
    {
      id: 22,
      src: "/logo/hf.png",
      srcDark: "",
      alt: "Huggingface logo",
      name: "Huggingface",
    },
    {
      id: 23,
      src: "/logo/langchain.png",
      srcDark: "",
      alt: "LangChain logo",
      name: "LangChain",
    },
  ],
  others: [
    {
      id: 24,
      src: "/logo/pusherjs.png",
      srcDark: "",
      alt: "Pusher JS logo",
      name: "Pusher",
    },
    {
      id: 25,
      src: "/logo/mapbox.png",
      srcDark: "",
      alt: "Mapbox logo",
      name: "Mapbox",
    },
  ],
};

export default logos;
